name: build+deploy

on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - name: Upload to S3
              run: |
                  export OLD_JS_FILENAME=$(aws s3 ls s3://$S3_BUCKET_NAME | grep ".\.js" | awk '{print $4}')
                  aws s3 sync --exclude *.txt ./dist/ s3://$S3_BUCKET_NAME
                  aws s3 rm s3://$S3_BUCKET_NAME/$OLD_JS_FILENAME
                  aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/"
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
                  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
                  AWS_DEFAULT_REGION: 'us-west-2'
